### ISSUE TITLE
[FEAT]Sign up link does not take you anywhere

### ISSUE THREAD

**Issue by Rithwik3425** [mohitparmar1/Shopy#10]
The sign up link in the login form does not take you to sign up form.

![image](https://github.com/mohitparmar1/Shopy/assets/132425133/f85080f5-66b0-4ab5-a96b-f18b9a250d36)

@mohitparmar1, if you can provide me with the necessary detail, I would like to work on this issue under @GSSOC'24

**Comment by Rithwik3425** [comment]
Kindly assign me this issue under GSSOC'24

**Comment by mohitparmar1** [comment]
hey, i have made one sign-up, could you just add the route for that!

**Comment by Rithwik3425** [comment]
sure, I will add the route connecting the sign up page

**Comment by mohitparmar1** [comment]
dont forget to star the repo!

**Comment by Rithwik3425** [comment]
Can you kindly assign this issue to me
