### ISSUE TITLE
Make description box functionable and responsive 

### ISSUE THREAD

**Issue by HimankPatidar** [mohitparmar1/Shopy#100]
In description box description and reviews are not functionable and also not responsive. @mohitparmar1  Can you assign me this issue under GSSOC24.

https://github.com/mohitparmar1/Shopy/assets/87924614/a3132d9c-1d11-4867-8710-9b86b172505f

**Comment by razerbotog** [comment]
i would love to resolve this issue. Please assign to me under GSSOC 24

**Comment by kashish-51** [comment]
Hey ! @mohitparmar1 I want to solve this issue. So can you please assign me this?

**Comment by Bishal-35** [comment]
@mohitparmar1 I would like to work on the issue under GSSOC'24
