### ISSUE TITLE
Adding icons to the navbar

### ISSUE THREAD

**Issue by harshmishra19** [mohitparmar1/Shopy#102]
- The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.
- I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

![Screenshot 2024-05-11 080754](https://github.com/mohitparmar1/Shopy/assets/115486960/deedfa28-9697-4516-bb21-03c1b9f8a793)
![Screenshot 2024-05-12 083752](https://github.com/mohitparmar1/Shopy/assets/115486960/bb98f374-80ea-4f56-b0fd-d6b19f2299bf)

**Comment by mohitparmar1** [comment]
not planned to add icons , you can work on different issues!
