### ISSUE TITLE
Home Page Responsive using tailwind css

### ISSUE THREAD

**Issue by Mr-ProgramerA** [mohitparmar1/Shopy#11]
![Screenshot (334)](https://github.com/mohitparmar1/Shopy/assets/65912700/eda0513a-79e7-4ad2-9b51-d572d4d8cd99)

I can make home page responsive using tailwind, can you assign me this under GSSOC24

**Comment by mohitparmar1** [comment]
It looks good but just make a card width little bigger!

**Comment by Mr-ProgramerA** [comment]
> It looks good but just make a card width little bigger!

Okay, should I wrap cards when screen size reduces i.e., in mobile view

**Comment by mohitparmar1** [comment]
yup, it will be great if you do this using a grid

**Comment by officeneerajsaini** [comment]
@mohitparmar1 you can close this issue .

**Comment by Mr-ProgramerA** [comment]
Done
