### ISSUE TITLE
Login signup Design

### ISSUE THREAD

**Issue by dhruv8433** [mohitparmar1/Shopy#115]
@mohitparmar1 

redesign login and signup page ui
![image](https://github.com/mohitparmar1/Shopy/assets/114583978/898c0040-b366-44db-9bcb-9f528d5b8d25)

**Comment by mohitparmar1** [comment]
hey, you have to pull the new changes!

**Comment by dhruv8433** [comment]
@mohitparmar1 i am checking in live web url and it give me 
![image](https://github.com/mohitparmar1/Shopy/assets/114583978/1ffa6d58-4228-42a3-a138-a8cad50384c5)

404 page not found
