### ISSUE TITLE
shop now button 

### ISSUE THREAD

**Issue by Varsani2520** [mohitparmar1/Shopy#116]
@mohitparmar1 user click on shop now button then display 404 page not found
![image](https://github.com/mohitparmar1/Shopy/assets/137641079/a446b714-069e-4bcb-bea1-9c8982095d24)
![image](https://github.com/mohitparmar1/Shopy/assets/137641079/a0b8bf42-3564-4d77-a5b0-6d9ba7ef55b9)

**Comment by Utkarsh7368** [comment]
Please assign this issue to me. I am Contributor at GSSOC'24

**Comment by mohitparmar1** [comment]
@Varsani2520 it's working!
