### ISSUE TITLE
💡[FEATURE]: Add search functionality

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [mohitparmar1/Shopy#136]
step 1. Add a search icon in the navbar, near the wish list icon.
step 2: Redirect to the search page, whenever user clicks on search icon.
step 3: There will be a search input and using that they can search.
step 4: Results will be shown in the same page.

Please assign this issue to me under GSSOC'24.

**Comment by HimankPatidar** [comment]
I want to work on this issue @mohitparmar1  can you assign me

**Comment by DharshiBalasubramaniyam** [comment]
@mohitparmar1, please assign this issue to me.
