### ISSUE TITLE
Landing page shop now button redirection issue

### ISSUE THREAD

**Issue by SMeenakshi15** [mohitparmar1/Shopy#15]
![Screenshot (110)](https://github.com/mohitparmar1/Shopy/assets/111890254/384ad4db-5d8b-4376-883a-9d9123775bf8)

Issue:
The Shop now button on home page doesn't redirect to the Women's page 

![image](https://github.com/mohitparmar1/Shopy/assets/111890254/20721c2f-ab95-473d-b631-b9526740ed88)

Please assign me this issue under GSSoC'24 I'll fix the redirection issue

**Comment by jaymehta002** [comment]
@mohitparmar1 @Rithwik3425 
Fixed this issue...

Created a pull Request
