### ISSUE TITLE
Notifying the user when the product is added to the cart

### ISSUE THREAD

**Issue by UjjwalGupta1105** [mohitparmar1/Shopy#17]
When we are hitting the Add to cart button it is not notifying the user that the product is added to the cart . 

![Shopy_Add_to_cart](https://github.com/mohitparmar1/Shopy/assets/165131091/edfc7d3b-11c4-484e-a272-dd4459f4666a)

So ,I want to add this feature that whenever the user hit the **Add to Cart button** it will show him a message **" Product Added To The Cart "**.

**Comment by mohitparmar1** [comment]
Thanks for bringing up the issue on our GitHub project! Your contribution is much appreciated!

**Comment by UjjwalGupta1105** [comment]
Thank you for assigning me this task .
