### ISSUE TITLE
Responsiveness of the discount tag and overflow texts

### ISSUE THREAD

**Issue by rahul-shrivastav** [mohitparmar1/Shopy#189]
![Screenshot 2024-05-22 010927](https://github.com/mohitparmar1/Shopy/assets/114675655/060f88f0-d43d-4c38-b587-a36e0f74dfde)

the responsiveness of text is not perfect and over flowing  , please assign this task to me under GSSOC 24

**Comment by nishant0708** [comment]
Hello , I'm interested in contributing to the project by implementing Support Us functionality. Could you please assign this task to me under GSSoC'24 with appropriate level?

**Comment by adil-techcode** [comment]
this issue solved,  please find another
