### ISSUE TITLE
Better Showcasing of products

### ISSUE THREAD

**Issue by rahul-shrivastav** [mohitparmar1/Shopy#190]
![Screenshot 2024-05-22 011352](https://github.com/mohitparmar1/Shopy/assets/114675655/66de1641-ac51-460b-95a2-2f27f01fa890)

Instead of showing them row-wise , by making all the products showint column wise will be better for user experience

I can do this proficiently , please assign this task to me under GSSOC 24. 
 Thanks

**Comment by divyanshu255** [comment]
I want to work on this under GSSOC24

**Comment by rahul-shrivastav** [comment]
No response
