### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by prasukjain07** [mohitparmar1/Shopy#197]
**Describe the bug**
When Screen width is decreased, some texts are overlap.

**Screenshots**

![image](https://github.com/mohitparmar1/Shopy/assets/115997785/9c026371-4eac-47b3-be99-3c9b63547b71)

 - Browser : Brave

**Comment by prasukjain07** [comment]
Please assign this issue to me under GSSoC'24

**Comment by mohitparmar1** [comment]
same issue! #84
