### ISSUE TITLE
[BUG]: enhancing the Login and Signup page

### ISSUE THREAD

**Issue by Ayush-may** [mohitparmar1/Shopy#36]
login page and signup page need to be improve , they arent matching with the website UI

addition content addition :
- add a google login and sign up button to register with google (only front end)

![image](https://github.com/mohitparmar1/Shopy/assets/112775332/25ae6844-133b-4fe9-9fcf-e2a3fecd49dd)

**Comment by Ayush-may** [comment]
assign me this issue under gssoc and pls add level to this

**Comment by Jish261203** [comment]
Hi there,

I'm enthusiastic about your app and would love to contribute to its improvement! Could you assign me the task  ? I have worked earlier on this for my project .

Looking forward to your response.

Best regards,
Jishnay

**Comment by Ayush-may** [comment]
@Jish261203  sorry but i already started working on this 
U can create a new another new issue
