### ISSUE TITLE
make cart page better

### ISSUE THREAD

**Issue by sahuf2003** [mohitparmar1/Shopy#53]
The cart page is overlapping with the footer

**Comment by sahuf2003** [comment]
@mohitparmar1    I  would like to work on this issue 
Im proficient in mern stafck

**Comment by adil-techcode** [comment]
@sahuf2003 , could you please provide a more detailed explanation of this issue? Additionally, if possible, include images or a video to help illustrate the problem.

**Comment by sahuf2003** [comment]
![image](https://github.com/mohitparmar1/Shopy/assets/127684377/6cce6159-7b02-4cbb-91a4-2384ef13b322)
when more products are added to cart it is overlapping with the footer so i will makete the chaanges accordingly so that It wont overlap

**Comment by sahuf2003** [comment]
![image](https://github.com/mohitparmar1/Shopy/assets/127684377/7fb0f83c-53f4-4e14-979a-e58c7125c9f0)
the cart is overlapping with the footer so I will improve the cart page
