### ISSUE TITLE
[STYLE] Improve the Styling of the footbar

### ISSUE THREAD

**Issue by aryansharma220** [mohitparmar1/Shopy#54]
![image](https://github.com/mohitparmar1/Shopy/assets/133234867/5ae82edc-7793-4dac-aa24-ee6c3eb282df)
The middle elements should be centered and there should be some padding from the left of the footer. Also we can remove the bottom scroll bar.

@mohitparmar1 Please assign it to me under Gssoc-24

**Comment by adil-techcode** [comment]
hello, this issue is already mentioned . work on different one
