### ISSUE TITLE
Make check now page

### ISSUE THREAD

**Issue by HimankPatidar** [mohitparmar1/Shopy#63]
there is no check now component in project . So, Can you assign this issue to me I can make check now page.

**Comment by HimankPatidar** [comment]
![Screenshot 2024-05-14 221156](https://github.com/mohitparmar1/Shopy/assets/87924614/32df0056-f8a5-49be-9cd1-afa1e8c1a5ff)
well here clicking check now button nothing happen i want to make a page about check now on clicking check now you can redirect to check now page

**Comment by adil-techcode** [comment]
@HimankPatidar

**Comment by HimankPatidar** [comment]
I merged this issue with PR #100 merge from there
