### ISSUE TITLE
Proceed To Checkout Activating Stripe

### ISSUE THREAD

**Issue by neelamnagarajgithub** [mohitparmar1/Shopy#66]
![image](https://github.com/mohitparmar1/Shopy/assets/113004986/be947fb0-283b-46cc-8b12-2f0efcc7e8e8)

Here when we click proceed to checkout at that point we can integrate  the payments powered by Stripe

Can you assign me this issue in GSSOC'24?

**Comment by mohitparmar1** [comment]
any updates?

**Comment by neelamnagarajgithub** [comment]
I will complete this issue by today

**Comment by neelamnagarajgithub** [comment]
I have completed the stripe integration for the procced to checkout button and connected it to Frontend
✅Created a Checkout session using Stripe
✅created a payment success page and also payment fail page
✅connected the frontend cart details and to the Stripe

Completed This Issue in the PR #160

**Comment by neelamnagarajgithub** [comment]
Hey @mohitparmar1  can u please add the labels??
