### ISSUE TITLE
[Bug]: Login and signup Form Validation failed

### ISSUE THREAD

**Issue by SaurabhS55** [mohitparmar1/Shopy#83]
Hey @mohitparmar1, I have just found one bug in login and signup forms. If we submit form without adding the values to it then also it submits and gave errors. 
screenshot:
![image](https://github.com/mohitparmar1/Shopy/assets/119050714/cbaff138-8cce-421c-9e2b-a188e87205aa)

I can fix this issue by using react form validations and also we can add sign in with google option to it.
I would like to work  on this issue , could you assign this issue to me under GSSOC'24 label?

**Comment by spywolf2049** [comment]
I am willing to work on this because i have experience in creating such websites. Please assign me this under GSSOC'24.

**Comment by SaurabhS55** [comment]
hey @mohitparmar1 could you label this issue under gssoc'24 label?
