### ISSUE TITLE
[Enhancement]  Add to Cart button doesn't respond on clicking

### ISSUE THREAD

**Issue by theeayushkumar** [mohitparmar1/Shopy#91]
When we are clicking the **Add to Cart** button, it simply adds the product to the cart without displaying any message.
 On clicking the **Add to Cart** button, it would look nice if the button would respond like **Added to Cart** successfully.
![image](https://github.com/mohitparmar1/Shopy/assets/128235540/c5a7c8a3-caf0-428f-acb7-60ca114ba477)
![image](https://github.com/mohitparmar1/Shopy/assets/128235540/15d090c4-4df3-4bca-956e-844298b146ea)

**Comment by mohitparmar1** [comment]
@theeayushkumar please pull the new changes!
