### ISSUE TITLE
Enhance UI Design for Login and Signup Pages

### ISSUE THREAD

**Issue by KARANSINGH34951** [mohitparmar1/Shopy#97]
I've noticed that the login and signup pages currently have a very basic design that could be enhanced to improve the overall user experience. As these pages are crucial for user interaction and account management, it's important to ensure that they are visually appealing.

<img width="960" alt="Screenshot 2024-05-13 005019" src="https://github.com/mohitparmar1/Shopy/assets/137412876/62e82c3c-eb28-45bf-8e14-fe278d9a69c0">
<img width="960" alt="Screenshot 2024-05-13 005027" src="https://github.com/mohitparmar1/Shopy/assets/137412876/e9c4dc27-9b13-4461-9c52-cd86f2e3be0f">

**Comment by Chelsea67jain** [comment]
@mohitparmar1 
I can improve the design of the login and signup page with social media integration and can add form validations to avoid 404 Vercel error. I have worked on the e-commerce platform previously.
Below is the link of GitHub repository.
https://github.com/Chelsea67jain/the_ultimate_garments
Can you allocate me this issue under GSSoC2024?

**Comment by mohitparmar1** [comment]
this issue has been solved!

**Comment by Chelsea67jain** [comment]
@mohitparmar1 Can you assign some me some other issue? I would like to work on this project under GSSoC2024.
